-- ============================================================
-- 007_hybrid_search.sql
-- Adds server-side hybrid search to poi_catalog.
--
-- What this adds:
--   1. pg_trgm extension  — character-level trigram similarity (Chinese-friendly)
--   2. Trigram GIN indexes on name + description (fast fuzzy keyword lookup)
--   3. search_vector generated column (tsvector for full-text search)
--   4. hybrid_search_poi_catalog() RPC — RRF fusion of vector + keyword search
--
-- When to use this RPC vs. the TypeScript hybrid-search.ts script:
--   - TypeScript script: development, batch testing, offline demo
--   - This RPC: production Next.js API route (Supabase BFF call), faster at scale
--
-- After applying this migration, the Next.js route can call:
--   supabase.rpc('hybrid_search_poi_catalog', { query_text, query_embedding, ... })
-- ============================================================

-- Step 1: Enable pg_trgm (character trigram similarity)
-- Works on Chinese because trigrams are character-level, not word-level.
-- Supabase enables this by default; the IF NOT EXISTS is a safety guard.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Step 2: Trigram GIN indexes for fast keyword search
-- Enables the % operator (trigram similarity) and LIKE/ILIKE acceleration.
CREATE INDEX IF NOT EXISTS poi_catalog_name_trgm
  ON poi_catalog USING gin (name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS poi_catalog_desc_trgm
  ON poi_catalog USING gin (description gin_trgm_ops);

-- Step 3: Full-text search vector (generated, stored)
-- Uses 'simple' config (no language-specific stemming):
--   'simple' = lowercase + strip accents, no stemming → correct for Chinese
--   'english' stemming would corrupt Chinese characters, so we use 'simple'.
-- Name weight A > description weight B > address weight C.
ALTER TABLE poi_catalog
  ADD COLUMN IF NOT EXISTS search_vector tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(name, '')),        'A') ||
    setweight(to_tsvector('simple', coalesce(description, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(address, '')),     'C')
  ) STORED;

CREATE INDEX IF NOT EXISTS poi_catalog_search_vector_idx
  ON poi_catalog USING gin (search_vector);

-- Step 4: hybrid_search_poi_catalog() RPC
-- Algorithm:
--   1. Vector search: finds semantically similar POIs via pgvector cosine distance
--   2. Keyword search: finds POIs matching query_text via trigram similarity
--      + full-text search (catches both fuzzy char overlap and exact terms)
--   3. RRF fusion: Reciprocal Rank Fusion with configurable alpha weighting
--      hybrid_score = alpha * 1/(rrf_k + vector_rank) + (1-alpha) * 1/(rrf_k + keyword_rank)
--
-- Parameters:
--   query_text      — raw query string (e.g. "下雨天室內景點")
--   query_embedding — 768-dim embedding from Gemini (generated by the caller)
--   match_threshold — minimum vector cosine similarity to include (default 0.3)
--   rrf_k           — RRF constant (default 60; higher = less top-rank bias)
--   match_count     — final result count (default 10)
--   alpha           — vector weight 0.0–1.0 (default 0.5; 1.0 = pure vector)
--   filter_metadata — jsonb filter applied to poi_catalog.metadata (same as match_poi_catalog)
--
CREATE OR REPLACE FUNCTION hybrid_search_poi_catalog(
  query_text       text,
  query_embedding  vector(768),
  match_threshold  float   DEFAULT 0.3,
  rrf_k            int     DEFAULT 60,
  match_count      int     DEFAULT 10,
  alpha            float   DEFAULT 0.5,
  filter_metadata  jsonb   DEFAULT '{}'::jsonb
)
RETURNS TABLE(
  id            uuid,
  name          text,
  metadata      jsonb,
  vector_rank   int,
  keyword_rank  int,
  hybrid_score  float,
  vector_score  float,
  keyword_score float
)
LANGUAGE sql STABLE AS $$

WITH

  -- ── Arm 1: Vector Search ────────────────────────────────────────────────
  -- Semantic: finds POIs by meaning, not exact words.
  -- Retrieves 2× match_count for RRF headroom.
  vector_results AS (
    SELECT
      pc.id,
      pc.name,
      pc.metadata,
      ROW_NUMBER() OVER (ORDER BY pc.embedding <=> query_embedding)  AS rank,
      1 - (pc.embedding <=> query_embedding)                          AS score
    FROM poi_catalog pc
    WHERE pc.embedding IS NOT NULL
      AND pc.metadata @> filter_metadata
      AND 1 - (pc.embedding <=> query_embedding) >= match_threshold
    ORDER BY pc.embedding <=> query_embedding
    LIMIT match_count * 2
  ),

  -- ── Arm 2: Keyword Search ───────────────────────────────────────────────
  -- Wide recall: catches exact name matches (e.g. "天元宮") that vector may rank low.
  -- keyword_score = weighted trigram similarity (name × 2 + description) / 3
  keyword_results AS (
    SELECT
      pc.id,
      pc.name,
      pc.metadata,
      ROW_NUMBER() OVER (
        ORDER BY (
          similarity(pc.name, query_text) * 2.0 +
          similarity(coalesce(pc.description, ''), query_text)
        ) DESC
      ) AS rank,
      (
        similarity(pc.name, query_text) * 2.0 +
        similarity(coalesce(pc.description, ''), query_text)
      ) / 3.0 AS score
    FROM poi_catalog pc
    WHERE pc.metadata @> filter_metadata
      AND (
        -- Trigram similarity (fuzzy character matching, good for Chinese)
        pc.name        % query_text  OR
        pc.description % query_text  OR
        -- Full-text match via search_vector (exact token match after 'simple' normalisation)
        pc.search_vector @@ plainto_tsquery('simple', query_text)
      )
    LIMIT match_count * 2
  ),

  -- ── Union candidates from both arms ────────────────────────────────────
  all_candidates AS (
    SELECT id, name, metadata FROM vector_results
    UNION
    SELECT id, name, metadata FROM keyword_results
  ),

  -- ── RRF Fusion ─────────────────────────────────────────────────────────
  -- For POIs not found in an arm, use penalty_rank = match_count * 2 + 1
  -- (effectively contributing ~0 to the score).
  rrf AS (
    SELECT
      ac.id,
      ac.name,
      ac.metadata,
      vr.rank                           AS v_rank,
      kr.rank                           AS k_rank,
      coalesce(vr.score, 0.0)           AS v_score,
      coalesce(kr.score, 0.0)           AS k_score,
      (
        alpha       * (1.0 / (rrf_k + coalesce(vr.rank, match_count * 2 + 1))) +
        (1.0 - alpha) * (1.0 / (rrf_k + coalesce(kr.rank, match_count * 2 + 1)))
      ) AS hybrid
    FROM all_candidates ac
    LEFT JOIN vector_results  vr ON vr.id = ac.id
    LEFT JOIN keyword_results kr ON kr.id = ac.id
  )

SELECT
  id,
  name,
  metadata,
  v_rank::int                      AS vector_rank,
  k_rank::int                      AS keyword_rank,
  round(hybrid::numeric, 6)        AS hybrid_score,
  round(v_score::numeric, 4)       AS vector_score,
  round(k_score::numeric, 4)       AS keyword_score
FROM rrf
ORDER BY hybrid DESC
LIMIT match_count;

$$;

-- ============================================================
-- Usage examples (from Next.js Route Handler):
--
--   const { data } = await supabase.rpc('hybrid_search_poi_catalog', {
--     query_text:      '下雨天室內景點',
--     query_embedding: embeddingArray,   // number[] from Gemini, length 768
--     match_threshold: 0.3,
--     match_count:     10,
--     alpha:           0.5,
--     filter_metadata: {},
--   })
--
-- Tune alpha per use case:
--   alpha = 0.7 → semantic-heavy (better for vibe queries like "文藝氣息")
--   alpha = 0.3 → keyword-heavy (better for exact name lookup like "天元宮")
--   alpha = 0.5 → balanced (default, good for mixed queries)
-- ============================================================
